-- MSR Recovery Slice v16 review note
--
-- v15/v15.1 audit findings on the restored MSR baseline:
--   * Defiant item rows exist and are preserved.
--   * Defiant merchant rows: 0
--   * Defiant NPC direct source rows: 0
--   * Defiant lootdrop_entries rows: 372 active before v16
--   * Defiant loottable links: 372 before v16
--
-- Promoted safe migration:
--   database/recovery/migrations_safe/080_disable_defiant_lootdrop_spawn_sources.sql
--
-- This disables Defiant lootdrop spawning by moving active lootdrop_entries.chance
-- to disabled_chance when needed and setting chance to 0. It intentionally does
-- not delete item rows, lootdrop rows, or loottable links.
--
-- Reversal, if needed during dev testing:
--   UPDATE lootdrop_entries lde
--   JOIN items i ON i.id = lde.item_id
--   SET lde.chance = lde.disabled_chance, lde.disabled_chance = 0
--   WHERE i.Name LIKE '%Defiant%'
--     AND lde.chance = 0
--     AND lde.disabled_chance > 0;
